### ISSUE TITLE
Sound is glitchy on ArchLinux with padsp (and without it)

### ISSUE THREAD

**Issue by forcegk** [stroucki/bb#1]
To reproduce:

Compile with:
   make CC=tcc
   cd mikunix
   make CC=tcc

Execute with padsp ./bb

Hopefully it is an easy fix. Also, what are the odds of a mikunix-backend/translation layer to mpv? That couuld be portable af.
Cheers!

**Comment by Jookia** [comment]
I've made a PR that should fix the glitchy audio.

**Comment by forcegk** [comment]
Damn that was an easy one. Thank you for taking the time to review the code!

**Comment by Jookia** [comment]
I initially thought this was a padsp issue or something but nope, just a classic C bug :)
